name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: mode directory
              run: cd /home/sasanqua/hosting/polaris/polaris-stage
            - name: git
              run: git pull
            - name: npm prepare
              run: npm install && npm build
            - name: npx build
              run: node .output/server/index.mjs -p 5001
