name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: npm prepare
              run: npm install && npm build
            - name: npx build
              run: node .output/server/index.mjs -p 5001
